-- DineNDash Seed Data
-- Clear existing data
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE reviews;
TRUNCATE TABLE booking_menu_items;
TRUNCATE TABLE bookings;
TRUNCATE TABLE time_slots;
TRUNCATE TABLE menu_items;
TRUNCATE TABLE dietary_preferences;
TRUNCATE TABLE restaurants;
TRUNCATE TABLE users;
SET FOREIGN_KEY_CHECKS = 1;

-- ============================================
-- USERS (Passwords are hashed version of 'password123')
-- ============================================
-- Hash: $2a$10$rM8LvH8Z8Z8Z8Z8Z8Z8Z8uK (This is a placeholder - will be generated by bcrypt in actual code)
INSERT INTO users (name, email, password, phone, role, is_active) VALUES
('Admin User', 'admin@dinendash.com', '$2a$10$quDb0wSKUkPDSsMattoyAOdHoV7J2mkFL93S1Jw6AD.501LifUyia', '9876543210', 'admin', TRUE),
('John Doe', 'john@example.com', '$2a$10$quDb0wSKUkPDSsMattoyAOdHoV7J2mkFL93S1Jw6AD.501LifUyia', '9876543211', 'customer', TRUE),
('Jane Smith', 'jane@example.com', '$2a$10$quDb0wSKUkPDSsMattoyAOdHoV7J2mkFL93S1Jw6AD.501LifUyia', '9876543212', 'customer', TRUE),
('Mike Johnson', 'mike@example.com', '$2a$10$quDb0wSKUkPDSsMattoyAOdHoV7J2mkFL93S1Jw6AD.501LifUyia', '9876543213', 'customer', TRUE),
('Sarah Williams', 'sarah@example.com', '$2a$10$quDb0wSKUkPDSsMattoyAOdHoV7J2mkFL93S1Jw6AD.501LifUyia', '9876543214', 'customer', TRUE);

-- ============================================
-- RESTAURANTS
-- ============================================
INSERT INTO restaurants (name, description, address, city, phone, email, cuisine_type, price_range, opening_time, closing_time, total_seats, image_url) VALUES
('The Italian Corner', 'Authentic Italian cuisine with a modern twist. Experience the taste of Italy in every bite.', '123 MG Road, Brigade Gateway', 'Bangalore', '9876543220', 'contact@italiancorner.com', 'Italian', '$$$', '11:00:00', '23:00:00', 60, 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'),
('Spice Garden', 'Traditional Indian flavors in an elegant setting. Perfect for family gatherings.', '456 Indiranagar Main Road', 'Bangalore', '9876543221', 'info@spicegarden.com', 'Indian', '$$', '12:00:00', '23:30:00', 80, 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800'),
('Sushi Paradise', 'Premium Japanese sushi and fine dining experience with master chefs.', '789 Whitefield Road', 'Bangalore', '9876543222', 'hello@sushiparadise.com', 'Japanese', '$$$$', '18:00:00', '23:00:00', 40, 'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800'),
('Green Bistro', 'Fresh, healthy continental cuisine. Farm to table dining experience.', '321 Koramangala 4th Block', 'Bangalore', '9876543223', 'contact@greenbistro.com', 'Continental', '$$', '10:00:00', '22:00:00', 50, 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800'),
('Dragon Wok', 'Authentic Chinese wok dishes and dim sum. A culinary journey to China.', '654 HSR Layout', 'Bangalore', '9876543224', 'info@dragonwok.com', 'Chinese', '$$', '11:30:00', '22:30:00', 70, 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800');

-- ============================================
-- DIETARY PREFERENCES
-- ============================================
INSERT INTO dietary_preferences (name, description) VALUES
('None', 'No specific dietary requirements'),
('Vegetarian', 'No meat or fish'),
('Vegan', 'No animal products'),
('Gluten-Free', 'No gluten-containing ingredients'),
('Halal', 'Halal certified food only'),
('Jain', 'No onion, garlic, or root vegetables'),
('Diabetic-Friendly', 'Low sugar options'),
('Lactose-Free', 'No dairy products');

-- ============================================
-- MENU ITEMS
-- ============================================
-- The Italian Corner (restaurant_id: 1)
INSERT INTO menu_items (restaurant_id, name, description, category, price, is_vegetarian, is_vegan, is_gluten_free, is_available) VALUES
(1, 'Margherita Pizza', 'Classic pizza with tomato sauce, mozzarella, and basil', 'main_course', 450.00, TRUE, FALSE, FALSE, TRUE),
(1, 'Spaghetti Carbonara', 'Creamy pasta with bacon, eggs, and parmesan', 'main_course', 550.00, FALSE, FALSE, FALSE, TRUE),
(1, 'Bruschetta', 'Toasted bread with tomatoes, garlic, and olive oil', 'appetizer', 250.00, TRUE, TRUE, FALSE, TRUE),
(1, 'Tiramisu', 'Classic Italian dessert with coffee and mascarpone', 'dessert', 300.00, TRUE, FALSE, FALSE, TRUE),
(1, 'Italian Red Wine', 'House special red wine', 'beverage', 800.00, TRUE, TRUE, TRUE, TRUE),

-- Spice Garden (restaurant_id: 2)
(2, 'Butter Chicken', 'Tender chicken in rich tomato and butter gravy', 'main_course', 420.00, FALSE, FALSE, TRUE, TRUE),
(2, 'Paneer Tikka Masala', 'Grilled cottage cheese in spicy tomato gravy', 'main_course', 380.00, TRUE, FALSE, TRUE, TRUE),
(2, 'Samosa', 'Crispy pastry filled with spiced potatoes', 'appetizer', 120.00, TRUE, TRUE, FALSE, TRUE),
(2, 'Gulab Jamun', 'Sweet milk dumplings in sugar syrup', 'dessert', 150.00, TRUE, FALSE, FALSE, TRUE),
(2, 'Mango Lassi', 'Refreshing yogurt drink with mango', 'beverage', 180.00, TRUE, FALSE, TRUE, TRUE),

-- Sushi Paradise (restaurant_id: 3)
(3, 'California Roll', 'Crab, avocado, and cucumber sushi roll', 'main_course', 650.00, FALSE, FALSE, TRUE, TRUE),
(3, 'Vegetable Tempura', 'Crispy fried assorted vegetables', 'appetizer', 450.00, TRUE, FALSE, FALSE, TRUE),
(3, 'Salmon Sashimi', 'Fresh raw salmon slices', 'main_course', 850.00, FALSE, FALSE, TRUE, TRUE),
(3, 'Mochi Ice Cream', 'Japanese rice cake with ice cream', 'dessert', 350.00, TRUE, FALSE, FALSE, TRUE),
(3, 'Sake', 'Traditional Japanese rice wine', 'beverage', 900.00, TRUE, TRUE, TRUE, TRUE),

-- Green Bistro (restaurant_id: 4)
(4, 'Grilled Chicken Salad', 'Fresh greens with grilled chicken breast', 'main_course', 480.00, FALSE, FALSE, TRUE, TRUE),
(4, 'Quinoa Buddha Bowl', 'Quinoa with roasted vegetables and tahini', 'main_course', 420.00, TRUE, TRUE, TRUE, TRUE),
(4, 'Caesar Salad', 'Romaine lettuce with Caesar dressing', 'appetizer', 320.00, FALSE, FALSE, FALSE, TRUE),
(4, 'Fruit Platter', 'Seasonal fresh fruits', 'dessert', 280.00, TRUE, TRUE, TRUE, TRUE),
(4, 'Fresh Juice', 'Freshly squeezed orange juice', 'beverage', 200.00, TRUE, TRUE, TRUE, TRUE),

-- Dragon Wok (restaurant_id: 5)
(5, 'Kung Pao Chicken', 'Spicy stir-fried chicken with peanuts', 'main_course', 460.00, FALSE, FALSE, TRUE, TRUE),
(5, 'Vegetable Fried Rice', 'Wok-tossed rice with mixed vegetables', 'main_course', 320.00, TRUE, FALSE, TRUE, TRUE),
(5, 'Spring Rolls', 'Crispy vegetable spring rolls', 'appetizer', 220.00, TRUE, TRUE, FALSE, TRUE),
(5, 'Honey Chilli Potato', 'Crispy potatoes in sweet and spicy sauce', 'appetizer', 260.00, TRUE, TRUE, TRUE, TRUE),
(5, 'Green Tea', 'Traditional Chinese green tea', 'beverage', 150.00, TRUE, TRUE, TRUE, TRUE);

-- ============================================
-- TIME SLOTS (Generate slots for next 7 days)
-- ============================================
-- This will be handled by a stored procedure or application code
-- For now, adding sample slots for today and tomorrow

-- Generate time slots for restaurants (11:00 AM to 10:00 PM, every 30 minutes)
-- Restaurant 1 - The Italian Corner
INSERT INTO time_slots (restaurant_id, slot_date, slot_time, available_seats) VALUES
(1, CURDATE(), '11:00:00', 60),
(1, CURDATE(), '11:30:00', 60),
(1, CURDATE(), '12:00:00', 60),
(1, CURDATE(), '12:30:00', 60),
(1, CURDATE(), '13:00:00', 60),
(1, CURDATE(), '18:00:00', 60),
(1, CURDATE(), '18:30:00', 60),
(1, CURDATE(), '19:00:00', 60),
(1, CURDATE(), '19:30:00', 60),
(1, CURDATE(), '20:00:00', 60),
(1, CURDATE(), '20:30:00', 60),
(1, CURDATE(), '21:00:00', 60),
(1, DATE_ADD(CURDATE(), INTERVAL 1 DAY), '11:00:00', 60),
(1, DATE_ADD(CURDATE(), INTERVAL 1 DAY), '12:00:00', 60),
(1, DATE_ADD(CURDATE(), INTERVAL 1 DAY), '19:00:00', 60),
(1, DATE_ADD(CURDATE(), INTERVAL 1 DAY), '20:00:00', 60);

-- Similar slots for other restaurants (abbreviated for brevity)
INSERT INTO time_slots (restaurant_id, slot_date, slot_time, available_seats)
SELECT 2, slot_date, slot_time, 80 FROM time_slots WHERE restaurant_id = 1;

INSERT INTO time_slots (restaurant_id, slot_date, slot_time, available_seats)
SELECT 3, slot_date, slot_time, 40 FROM time_slots WHERE restaurant_id = 1;

INSERT INTO time_slots (restaurant_id, slot_date, slot_time, available_seats)
SELECT 4, slot_date, slot_time, 50 FROM time_slots WHERE restaurant_id = 1;

INSERT INTO time_slots (restaurant_id, slot_date, slot_time, available_seats)
SELECT 5, slot_date, slot_time, 70 FROM time_slots WHERE restaurant_id = 1;

-- ============================================
-- SAMPLE BOOKINGS
-- ============================================
INSERT INTO bookings (booking_reference, user_id, restaurant_id, booking_date, booking_time, number_of_seats, dietary_preference_id, special_requests, status) VALUES
('BK2024001', 2, 1, DATE_ADD(CURDATE(), INTERVAL 2 DAY), '19:00:00', 4, 1, 'Window seat preferred', 'approved'),
('BK2024002', 3, 2, DATE_ADD(CURDATE(), INTERVAL 3 DAY), '20:00:00', 2, 2, 'Anniversary celebration', 'pending'),
('BK2024003', 4, 3, DATE_ADD(CURDATE(), INTERVAL 1 DAY), '19:30:00', 3, 4, 'Allergy to shellfish', 'approved'),
('BK2024004', 5, 4, DATE_ADD(CURDATE(), INTERVAL 4 DAY), '18:00:00', 2, 3, NULL, 'pending');

-- ============================================
-- SAMPLE BOOKING MENU ITEMS
-- ============================================
INSERT INTO booking_menu_items (booking_id, menu_item_id, quantity, price_at_booking) VALUES
(1, 1, 2, 450.00),
(1, 2, 1, 550.00),
(1, 5, 1, 800.00),
(3, 11, 2, 650.00),
(3, 14, 3, 350.00);

-- ============================================
-- SAMPLE REVIEWS
-- ============================================
INSERT INTO reviews (user_id, restaurant_id, booking_id, rating, comment) VALUES
(2, 1, 1, 5, 'Absolutely amazing experience! The food was delicious and service was impeccable.'),
(4, 3, 3, 4, 'Great sushi quality. Atmosphere could be better but overall worth it.');

-- Display summary
SELECT 'Database seeded successfully!' as message;
SELECT COUNT(*) as total_users FROM users;
SELECT COUNT(*) as total_restaurants FROM restaurants;
SELECT COUNT(*) as total_menu_items FROM menu_items;
SELECT COUNT(*) as total_bookings FROM bookings;
SELECT COUNT(*) as total_reviews FROM reviews;